import {useEffect,useState} from 'react';
import {Text,Platform} from 'react-native';
import DateTimePicker from '@react-native-community/datetimepicker';
import {Redirect,router} from 'expo-router';
import {useSession} from '../lib/session';
import type {BookingOptions} from '../lib/types';
import {Screen,Card,Field,Action,ErrorText,s} from '../components/ui';
import {ChoiceField} from '../components/choice';
export default function Book(){const {session,call}=useSession();const [options,setOptions]=useState<BookingOptions|null>(null);const [patient,setPatient]=useState('');const [doctor,setDoctor]=useState('');const [service,setService]=useState('');const [date,setDate]=useState(()=>new Date(Date.now()+86400000));const [earliest]=useState(()=>new Date());const [picker,setPicker]=useState<'date'|'time'|null>(null);const [symptoms,setSymptoms]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);useEffect(()=>{void call<BookingOptions>('booking-options/').then(value=>{setOptions(value);if(value.patients.length===1)setPatient(String(value.patients[0].id));if(value.doctors.length===1)setDoctor(String(value.doctors[0].id));if(value.services.length===1)setService(String(value.services[0].id));}).catch(e=>setError((e as Error).message));},[call]);if(!session)return <Redirect href="/"/>;
  async function submit(){setBusy(true);setError('');const pad=(v:number)=>String(v).padStart(2,'0');const local=`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}:00+02:00`;try{await call('appointments/',{patient,practitioner:doctor,service,starts_at:local,reason_for_visit:symptoms});router.replace('/home');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Screen title="Request an appointment" subtitle="Reception reviews your request, then your doctor confirms the time."><Card>{options&&<><ChoiceField label="Patient" choices={options.patients} value={patient} onChange={setPatient}/><ChoiceField label="Doctor" choices={options.doctors} value={doctor} onChange={setDoctor}/><ChoiceField label="Consultation" choices={options.services} value={service} onChange={setService}/>{!options.patients.length&&<Text style={s.text}>Ask reception to link your patient record to your app account.</Text>}</>}<Action secondary label={`Date: ${date.toLocaleDateString()}`} onPress={()=>setPicker('date')}/><Action secondary label={`Time (SAST): ${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`} onPress={()=>setPicker('time')}/>{picker&&<><DateTimePicker value={date} mode={picker} display={Platform.OS==='ios'?'spinner':'default'} is24Hour minimumDate={picker==='date'?earliest:undefined} onChange={(event,value)=>{if(Platform.OS==='android')setPicker(null);if(value)setDate(value);}}/>{Platform.OS==='ios'&&<Action secondary label="Done" onPress={()=>setPicker(null)}/>}</>}<Field label="Reported symptoms / reason for visit" value={symptoms} onChangeText={setSymptoms} multiline/><ErrorText message={error}/><Action label="Send appointment request" onPress={()=>void submit()} busy={busy} disabled={!patient||!doctor||!service||!symptoms.trim()}/><Action label="Cancel" secondary onPress={()=>router.replace('/home')}/></Card></Screen>;
}
