import {useCallback,useEffect,useState} from 'react';
import {View,Text,Pressable,ActivityIndicator,AppState,Alert,Platform} from 'react-native';
import {Redirect,router} from 'expo-router';
import * as Notifications from 'expo-notifications';
import {useSession} from '../lib/session';
import {registerPush} from '../lib/push';
import type {Appointment,Dashboard} from '../lib/types';
import {Screen,Card,Action,ErrorText,s,colors} from '../components/ui';
export default function Home(){const {session,call,signOut}=useSession();const [data,setData]=useState<Dashboard|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [tab,setTab]=useState<'appointments'|'notifications'|'prescriptions'>('appointments');
  const refresh=useCallback(async()=>{try{setData(await call<Dashboard>('dashboard/'));setError('');}catch(e){setError((e as Error).message);}},[call]);
  useEffect(()=>{if(!session)return;const initial=setTimeout(()=>{if(Notifications.getLastNotificationResponse()){setTab('notifications');Notifications.clearLastNotificationResponse();}void refresh();},0);const timer=setInterval(()=>{if(AppState.currentState==='active')void refresh();},15000);const active=AppState.addEventListener('change',state=>{if(state==='active')void refresh();});const received=Notifications.addNotificationReceivedListener(()=>void refresh());const tapped=Notifications.addNotificationResponseReceivedListener(()=>{setTab('notifications');Notifications.clearLastNotificationResponse();void refresh();});return()=>{clearTimeout(initial);clearInterval(timer);active.remove();received.remove();tapped.remove();};},[session,refresh]);
  async function action(visit:Appointment,operation:string){setBusy(true);setError('');try{await call(`appointments/${visit.id}/${operation}/`,{});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const confirm=(visit:Appointment,operation:string,label:string)=>Alert.alert(label,operation==='doctor-approve'?`Confirm ${visit.patient}'s appointment for ${visit.time}?`:`${label} for ${visit.patient}?`,[{text:'Cancel',style:'cancel'},{text:'Confirm',onPress:()=>void action(visit,operation)}]);
  async function enablePush(){setBusy(true);try{await registerPush(token=>call('devices/',{token,platform:Platform.OS}).then(()=>{}));Alert.alert('Phone notifications enabled','Your phone is registered. Delivery also depends on your practice notification service.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(!session)return <Redirect href="/"/>;
  const role=session.session.role;const reception=['owner','reception'].includes(role);const doctor=role==='doctor';const next=data?.next_patient;
  return <Screen title={doctor?`${session.session.user} — Clinical workspace`:reception?'Reception workspace':'Your care'} subtitle={`${session.session.practice.name} · Hello ${session.session.user}`}>
    <View style={s.row}><View style={s.stat}><Text style={s.number}>{data?.today_count??'—'}</Text><Text style={s.small}>Appointments today</Text></View><View style={s.stat}><Text style={s.number}>{data?.unread??'—'}</Text><Text style={s.small}>Personal updates</Text></View></View>
    <ErrorText message={error}/>{!data&&!error&&<ActivityIndicator style={{margin:20}} color={colors.teal}/>}
    {doctor&&<Card><Text style={s.heading}>Next patient</Text>{next?<><Text style={s.heading}>{next.patient}</Text><Text style={s.text}>{next.time}</Text><Text style={s.text}>Reported symptoms: {next.symptoms||'Not yet recorded'}</Text><Text style={s.text}>Blood pressure: {next.bp}</Text><Text style={s.badge}>{next.called?'Patient called':next.doctor_approved?'Approved by you':'Awaiting your review'}</Text>{!next.doctor_approved&&<Action label="Approve & notify patient" disabled={busy} onPress={()=>confirm(next,'doctor-approve','Approve appointment')}/>} {next.can_call&&<Action label="Ready now · notify patient" disabled={busy} onPress={()=>confirm(next,'call','Ready now')}/>}</>:<Text style={s.text}>No patients waiting. Reception-approved visits will appear here.</Text>}</Card>}
    <Action label="My Health" secondary onPress={()=>router.push('/my-health')}/><Action label="Request an appointment" onPress={()=>router.push('/book')}/>{doctor&&<Action label="Create prescription draft" secondary onPress={()=>router.push('/prescription')}/>} {reception&&<Action label="Register a patient" secondary onPress={()=>router.push('/register-patient')}/>}
    {reception&&<Action label="Manage registrations" secondary onPress={()=>router.push('/registrations')}/>}
    {reception&&<Action label="Scan patient document" secondary onPress={()=>router.push('/scan-document')}/>}
    <View style={s.tabs}>{(['appointments','notifications','prescriptions'] as const).map(item=><Pressable key={item} accessibilityRole="tab" accessibilityState={{selected:tab===item}} onPress={()=>setTab(item)} style={[s.tab,tab===item&&s.tabActive]}><Text style={{fontSize:11,fontWeight:'600',color:colors.ink}}>{item==='notifications'?'Updates':item==='prescriptions'?'Prescriptions':'Visits'}</Text></Pressable>)}</View>
    {tab==='appointments'&&data?.appointments.map(visit=><Card key={visit.id}><Text style={s.heading}>{visit.patient}</Text><Text style={s.text}>{visit.time}</Text><Text style={s.text}>{visit.service} · Dr {visit.doctor}</Text><Text style={s.badge}>{visit.status==='held'?'Reception approved':visit.status.replace('_',' ')}{visit.doctor_approved?' · Doctor approved':''}</Text>{(reception||doctor)&&<><Text style={s.text}>Reported symptoms: {visit.symptoms||'Not yet recorded'}</Text><Text style={s.text}>Blood pressure: {visit.bp}</Text></>}
      {reception&&!visit.doctor_approved&&['requested','held','confirmed','arrived'].includes(visit.status)&&<Action secondary label="Record symptoms & blood pressure" onPress={()=>router.push({pathname:'/intake',params:{id:visit.id,symptoms:visit.symptoms,systolic:visit.blood_pressure_systolic??'',diastolic:visit.blood_pressure_diastolic??''}})}/>}
      {reception&&visit.status==='requested'&&<><Action label="Approve for doctor review" disabled={busy} onPress={()=>confirm(visit,'approve','Reception approval')}/><Action label="Reject request" secondary onPress={()=>router.push({pathname:'/intake',params:{id:visit.id,reject:'yes'}})}/></>}
      {doctor&&['held','confirmed','arrived'].includes(visit.status)&&<>{!visit.doctor_approved?<Action label="Approve & notify patient" disabled={busy} onPress={()=>confirm(visit,'doctor-approve','Approve appointment')}/>:<><Action label="Open consultation" secondary disabled={busy} onPress={()=>void action(visit,'encounter')}/>{visit.has_consultation&&<Action label="Complete consultation" secondary disabled={busy} onPress={()=>confirm(visit,'complete','Complete consultation')}/>}</>}</>}</Card>)}
    {tab==='appointments'&&data&&!data.appointments.length&&<Card><Text style={s.text}>No appointments yet. Your visits will appear here after booking.</Text></Card>}
    {tab==='notifications'&&<><Action label="Enable phone notifications" secondary busy={busy} onPress={()=>void enablePush()}/>{data?.notifications.map(notice=><Card key={notice.id}><Text style={s.heading}>{notice.title}</Text><Text style={s.text}>{notice.message}</Text>{!notice.read_at&&<Action label="Mark as read" secondary onPress={()=>{void call(`notifications/${notice.id}/read/`,{}).then(refresh).catch(e=>setError((e as Error).message));}}/>}</Card>)}{data&&!data.notifications.length&&<Card><Text style={s.text}>Your personal updates will appear here.</Text></Card>}</>}
    {tab==='prescriptions'&&data?.prescriptions.map(rx=><Card key={rx.id}><Text style={s.heading}>{rx.patient}</Text><Text style={s.badge}>{rx.status}</Text>{rx.items.map(item=><View key={item.id}><Text style={s.text}>{item.medication_name} · {item.dosage} · {item.frequency}{item.duration?` · ${item.duration}`:''}</Text>{!!item.route&&<Text style={s.text}>Route: {item.route}</Text>}{!!item.quantity&&<Text style={s.text}>Quantity: {item.quantity}</Text>}{!!item.instructions&&<Text style={s.text}>{item.instructions}</Text>}</View>)}<Text style={s.text}>{rx.general_instructions}</Text>{doctor&&rx.status==='draft'&&<Action label="Review & issue prescription" secondary onPress={()=>Alert.alert('Issue this prescription?','Confirm that you reviewed the medication, dosage and instructions shown above.',[{text:'Cancel',style:'cancel'},{text:'I reviewed it · issue',onPress:()=>{void call(`prescriptions/${rx.id}/issue/`,{reviewed:true}).then(refresh).catch(e=>setError((e as Error).message));}}])}/>}</Card>)}
    {tab==='prescriptions'&&data&&!data.prescriptions.length&&<Card><Text style={s.text}>No prescriptions available in this workspace.</Text></Card>}
    <Action label="Refresh" secondary onPress={()=>void refresh()}/><Action label="Sign out" secondary onPress={()=>{void signOut().catch(e=>setError((e as Error).message));}}/><Text style={s.small}>Times are South African time (SAST). Your practice manages your account.</Text>
  </Screen>;
}
