import {useCallback,useEffect,useState} from 'react';
import {Text} from 'react-native';
import {Redirect,router} from 'expo-router';
import {Screen,Card,Field,Action,ErrorText} from '../components/ui';
import {useSession} from '../lib/session';
type Patient={id:string;name:string;file_number:string};
type Entry={id:number;kind:string;data:Record<string,string|number>;recorded_at:string;reviewed:boolean};
type Health={entries:Entry[];trends:Record<string,{latest:number;change:number|null}>;reminders:string[];summary:string};
const fields:Record<string,string[]>={vitals:['systolic','diastolic','heart_rate','temperature','oxygen','weight','notes'],wellness:['walk_minutes','exercise_minutes','meditation_minutes','sleep_hours','nutrition','notes'],report:['category','title','summary']};
const label=(key:string)=>key.replaceAll('_',' ');
export default function MyHealth(){
 const {session,call}=useSession();const [patients,setPatients]=useState<Patient[]>([]);const [patient,setPatient]=useState('');const [health,setHealth]=useState<Health|null>(null);const [kind,setKind]=useState('wellness');const [values,setValues]=useState<Record<string,string>>({});const [editing,setEditing]=useState<number|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const staff=session?.session.role!=='patient';
 useEffect(()=>{call<Patient[]>('health/patients/').then(items=>{setPatients(items);setPatient(items[0]?.id||'');}).catch(e=>setError(e.message));},[call]);
 const refresh=useCallback(async()=>{if(patient){const result=await call<Health>(`health/${patient}/`);setHealth(result);}},[patient,call]);
 useEffect(()=>{let active=true;if(patient)void call<Health>(`health/${patient}/`).then(result=>{if(active)setHealth(result);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[patient,call]);
 if(!session)return <Redirect href="/"/>;
 async function save(){setBusy(true);setError('');try{await call(`health/${patient}/${editing?editing+'/':''}`,{kind,data:values},editing?'PATCH':'POST');setEditing(null);setValues({});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Screen title="My Health" subtitle="Your measurements, reports and daily wellbeing."><Action label="Back to dashboard" secondary onPress={()=>router.back()}/><ErrorText message={error}/><Card><Text>Select patient</Text>{patients.map(p=><Action key={p.id} label={`${p.name} · ${p.file_number}${patient===p.id?' ✓':''}`} secondary onPress={()=>{setHealth(null);setEditing(null);setValues({});setKind('wellness');setPatient(p.id);}}/>)}{!patients.length&&<Text>No linked patient records.</Text>}</Card>{health&&<><Card><Text>Recent trends</Text>{Object.entries(health.trends).map(([key,value])=><Text key={key}>{label(key)}: {value.latest} · {value.change===null?'First reading':`Change ${value.change}`}</Text>)}<Text>{health.summary}</Text>{health.reminders.map(item=><Text key={item}>{item}</Text>)}</Card><Card><Text>{editing?'Edit record':'Add a record'}</Text>{!editing&&(staff?['wellness','vitals','report']:['wellness']).map(section=><Action key={section} label={section===kind?`${section} ✓`:section} secondary onPress={()=>{setKind(section);setValues({});}}/>)}{fields[kind].map(key=><Field key={key} label={label(key)} value={values[key]||''} onChangeText={value=>setValues(old=>({...old,[key]:value}))}/>)}<Action label="Save record" busy={busy} onPress={()=>void save()}/>{editing&&<Action label="Cancel edit" secondary onPress={()=>{setEditing(null);setValues({});}}/>}</Card>{health.entries.map(entry=><Card key={entry.id}><Text>{entry.kind} · {new Date(entry.recorded_at).toLocaleString()}</Text><Text>{entry.reviewed?'Reviewed':'Not reviewed'}</Text>{Object.entries(entry.data).map(([key,value])=><Text key={key}>{label(key)}: {value}</Text>)}{(staff||entry.kind==='wellness')&&<Action label="Edit" secondary onPress={()=>{setKind(entry.kind);setEditing(entry.id);setValues(Object.fromEntries(Object.entries(entry.data).map(([k,v])=>[k,String(v)])));}}/>}{['owner','doctor'].includes(session.session.role)&&!entry.reviewed&&<Action label="Mark reviewed" secondary onPress={()=>{void call(`health/${patient}/${entry.id}/`,{review:true},'PATCH').then(refresh).catch(e=>setError(e.message));}}/>}</Card>)}</>}<Card><Text>Record laboratory, X-ray and vision report summaries here. Source documents remain in the practice document workflow. Live device readings require device integration.</Text></Card></Screen>;
}
