import {useEffect,useState} from 'react';
import {Text,Alert} from 'react-native';
import {Redirect,router} from 'expo-router';
import {Screen,Card,Field,Action,ErrorText} from '../components/ui';
import {useSession} from '../lib/session';
type Item={id:string|number;active:boolean;[key:string]:string|number|boolean|null};
type Directory={patients:Item[];accounts:Item[]};
export default function Registrations(){const {session,call}=useSession();const [directory,setDirectory]=useState<Directory|null>(null);const [type,setType]=useState('patients');const [selected,setSelected]=useState<Item|null>(null);const [values,setValues]=useState<Record<string,string>>({});const [creating,setCreating]=useState(false);const [role,setRole]=useState('patient');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
useEffect(()=>{void call<Directory>('registrations/').then(setDirectory).catch(e=>setError(e.message));},[call]);
if(!session)return <Redirect href="/"/>;if(!['owner','reception'].includes(session.session.role))return <Redirect href="/home"/>;
async function refresh(){setDirectory(await call<Directory>('registrations/'));}
async function save(){setBusy(true);setError('');try{if(creating)await call('registrations/',{...values,role,delivery:'password'});else if(selected)await call(`registrations/${type}/${selected.id}/`,values,'PATCH');setSelected(null);setCreating(false);setValues({});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
function choose(item:Item,section:string){setType(section);setSelected(item);setCreating(false);setValues(Object.fromEntries(Object.entries(item).filter(([k])=>!['id','active','portal_user','role'].includes(k)).map(([k,v])=>[k,String(v??'')])));}
function toggle(item:Item,section:string){Alert.alert(item.active?'Disable / archive?':'Restore?', 'Records are retained.',[{text:'Cancel',style:'cancel'},{text:'Confirm',onPress:()=>{void call(`registrations/${section}/${item.id}/`,{active:!item.active},'PATCH').then(refresh).catch(e=>setError(e.message));}}]);}
return <Screen title="Manage registrations" subtitle="Patient details and practice account access"><Action label="Back" secondary onPress={()=>router.back()}/><ErrorText message={error}/><Action label="Register patient record" onPress={()=>router.push('/register-patient')}/><Action label="Create doctor / patient login" onPress={()=>{setCreating(true);setSelected(null);setValues({});}}/>{(selected||creating)&&<Card>{creating&&<><Action label={`Account role: ${role} (tap to change)`} secondary onPress={()=>{setRole(role==='patient'?'doctor':'patient');setValues({});}}/>{role==='patient'&&directory?.patients.filter(p=>p.active&&!p.portal_user).map(p=><Action key={p.id} label={`${p.given_name} ${p.family_name}${values.patient===String(p.id)?' ✓':''}`} secondary onPress={()=>setValues(old=>({...old,patient:String(p.id)}))}/>)}</>}{(creating?['username','first_name','last_name','email','password1','password2']:Object.keys(values)).map(key=><Field key={key} label={key.replaceAll('_',' ')} value={values[key]||''} onChangeText={value=>setValues(old=>({...old,[key]:value}))} secret={key.startsWith('password')}/>)}<Action label="Save registration" busy={busy} onPress={()=>void save()}/><Action label="Cancel" secondary onPress={()=>{setSelected(null);setCreating(false);}}/></Card>}{directory&&(['patients','accounts'] as const).map(section=><Card key={section}><Text>{section==='patients'?'Patient records':'Doctor and patient accounts'}</Text>{directory[section].map(item=><Card key={item.id}><Text>{section==='patients'?`${item.given_name} ${item.family_name}`:`${item.username} · ${item.role}`}</Text><Text>{item.active?'Active':'Archived / disabled'}</Text><Action label="Edit details" secondary onPress={()=>choose(item,section)}/><Action label={item.active?(section==='patients'?'Archive patient':'Disable access'):'Restore'} secondary onPress={()=>toggle(item,section)}/></Card>)}</Card>)}</Screen>;
}
