# Generated by Django 5.2.17 on 2026-10-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("appointment_approved", "Appointment approved"),
                    ("appointment_rejected", "Appointment rejected"),
                    ("appointment_reminder", "Appointment reminder"),
                ],
                max_length=32,
            ),
        ),
    ]
