# Generated by Django 5.2.17 on 2026-10-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('appointment_approved', 'Appointment approved'), ('appointment_rejected', 'Appointment rejected'), ('doctor_ready', 'Doctor approved appointment'), ('patient_called', 'Doctor ready now'), ('appointment_reminder', 'Appointment reminder')], max_length=32),
        ),
    ]
