import os
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PRODUCTION_MODE = os.environ.get("DJANGO_PRODUCTION", "False").lower() in {"true", "1", "yes"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-development-only",
)

DEBUG = os.environ.get(
    "DJANGO_DEBUG",
    "True",
).lower() in {
    "1",
    "true",
    "yes",
}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS",
        "localhost,127.0.0.1",
    ).split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "",
    ).split(",")
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "tenancy",
    "portal",
    "securityguard",
    "django_otp",
    "django_otp.plugins.otp_totp",
    "patients",
    "scheduling",
    "notifications",
    "clinical",
    "documents",
    "payments",
    "auditlog",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "portal.middleware.PortalTimezoneMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "securityguard.middleware.SecurityGuardMiddleware",
    "securityguard.access.MFAAccessMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get("POSTGRES_DB"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["POSTGRES_DB"],
            "USER": os.environ["POSTGRES_USER"],
            "PASSWORD": os.environ["POSTGRES_PASSWORD"],
            "HOST": os.environ.get("POSTGRES_HOST", "db"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": int(
                os.environ.get("POSTGRES_CONN_MAX_AGE", "60")
            ),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 12},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DOCUMENT_STORAGE_ROOT = Path(os.environ.get("DOCUMENT_STORAGE_ROOT", str(BASE_DIR / "private_documents")))
DOCUMENT_DOWNLOAD_TOKEN_MAX_AGE = int(
    os.environ.get("DOCUMENT_DOWNLOAD_TOKEN_MAX_AGE", "300")
)
CLAMAV_HOST = os.environ.get("CLAMAV_HOST", "127.0.0.1")
CLAMAV_PORT = int(os.environ.get("CLAMAV_PORT", "3310"))
CLAMAV_TIMEOUT = int(os.environ.get("CLAMAV_TIMEOUT", "30"))

if not DEBUG:
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )
    SECURE_SSL_REDIRECT = os.environ.get(
        "DJANGO_SECURE_SSL_REDIRECT",
        "True",
    ).lower() in {
        "1",
        "true",
        "yes",
    }
    SECURE_HSTS_SECONDS = int(
        os.environ.get(
            "DJANGO_SECURE_HSTS_SECONDS",
            "300" if PRODUCTION_MODE else "0",
        )
    )
    # Enable these only after verifying every affected subdomain supports HTTPS.
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get("DJANGO_HSTS_INCLUDE_SUBDOMAINS", "False").lower() == "true"
    SECURE_HSTS_PRELOAD = os.environ.get("DJANGO_HSTS_PRELOAD", "False").lower() == "true"

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 8 * 60 * 60
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_IDLE_TIMEOUT = 30 * 60
SESSION_ABSOLUTE_TIMEOUT = 8 * 60 * 60
LOGIN_ACCOUNT_LIMIT = 5
LOGIN_ADDRESS_LIMIT = 100
LOGIN_ATTEMPT_WINDOW = 15 * 60
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"
# Deliberate staged HSTS rollout: do not force policies on other hostnames or
# request permanent browser preloading before the operator verifies them.
SILENCED_SYSTEM_CHECKS = ["security.W005", "security.W021"]
DATA_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024

# Browser APIs use CSRF-protected sessions. Native bearer authentication, when
# deployed, is declared by the mobile views rather than HTTP Basic defaults.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ["rest_framework.authentication.SessionAuthentication"],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
}

LOGIN_URL = "/app/login/"
LOGIN_REDIRECT_URL = "/app/"
LOGOUT_REDIRECT_URL = "/app/login/"

# External services stay disabled until their credentials and stable origin are set.
PUBLIC_BASE_URL = os.environ.get("MEDIFLOW_PUBLIC_URL", "").rstrip("/")
EMAIL_ENABLED = os.environ.get("MEDIFLOW_EMAIL_ENABLED", "False").lower() == "true"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = True
EMAIL_TIMEOUT = 15
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "")
PASSWORD_RESET_TIMEOUT = 3600
ADMIN_MFA_REQUIRED = os.environ.get("MEDIFLOW_ADMIN_MFA_REQUIRED", str(PRODUCTION_MODE)).lower() == "true"
OTP_TOTP_ISSUER = "MediFlow"
OTP_TOTP_THROTTLE_FACTOR = 2
PRIVACY_CONTACT = os.environ.get("MEDIFLOW_PRIVACY_CONTACT", "")
PRACTICE_OPERATOR = os.environ.get("MEDIFLOW_OPERATOR", "")
LOGGING = {
    "version": 1, "disable_existing_loggers": False,
    "filters": {"secret_paths": {"()": "securityguard.logging.SecretPathFilter"}},
    "handlers": {"console": {"class": "logging.StreamHandler", "filters": ["secret_paths"]},
                 "operations": {"class": "securityguard.logging.OperationalErrorHandler", "level": "ERROR"}},
    "loggers": {
        "django.security.csrf": {"handlers": ["console"], "level": "WARNING", "propagate": False},
        "django.request": {"handlers": ["console", "operations"], "level": "ERROR", "propagate": False},
    },
}

OPERATIONS_EMAIL = os.environ.get("MEDIFLOW_OPERATIONS_EMAIL", "")
BACKUP_ROOT = Path(os.environ.get("MEDIFLOW_BACKUP_ROOT", "/backups"))
EXTERNAL_MONITOR_CONFIGURED = os.environ.get("MEDIFLOW_EXTERNAL_MONITOR_CONFIGURED", "False").lower() == "true"
OFFSITE_BACKUP_REQUIRED = os.environ.get("MEDIFLOW_OFFSITE_BACKUP_REQUIRED", "False").lower() == "true"

RETENTION_NOTICE = os.environ.get("MEDIFLOW_RETENTION_NOTICE", "")
