import React from 'react';
import {View,Text,TextInput,Pressable,StyleSheet,ScrollView,KeyboardAvoidingView,Platform,ActivityIndicator} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import Svg,{Rect,Path} from 'react-native-svg';
export const colors={teal:'#126b80',ink:'#183942',muted:'#617981',line:'#dce8eb',bg:'#f3f8fa'};
export function Logo(){return <View style={s.brand}><Svg width={43} height={43} viewBox="0 0 64 64"><Rect width={64} height={64} rx={18} fill={colors.teal}/><Path d="M26 13h12v13h13v12H38v13H26V38H13V26h13z" fill="#fff"/><Path d="M12 33h11l5-9 7 19 5-10h12" fill="none" stroke="#66e0d0" strokeWidth={3} strokeLinecap="round" strokeLinejoin="round"/></Svg><View><Text style={s.brandText}>Medi<Text style={{color:colors.teal}}>Flow</Text></Text><Text style={s.caption}>YOUR CARE, YOUR TIME</Text></View></View>;}
export function Screen({children,title,subtitle}:{children:React.ReactNode;title:string;subtitle?:string}){return <SafeAreaView style={s.screen}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}><Logo/><Text style={s.title}>{title}</Text>{subtitle&&<Text style={s.muted}>{subtitle}</Text>}{children}</ScrollView></KeyboardAvoidingView></SafeAreaView>;}
export function Card({children}:{children:React.ReactNode}){return <View style={s.card}>{children}</View>;}
export function Action({label,onPress,secondary=false,disabled=false,busy=false}:{label:string;onPress:()=>void;secondary?:boolean;disabled?:boolean;busy?:boolean}){return <Pressable accessibilityRole="button" accessibilityState={{disabled:disabled||busy,busy}} disabled={disabled||busy} onPress={onPress} style={({pressed})=>[s.button,secondary&&s.secondary,(disabled||busy)&&{opacity:.5},pressed&&{opacity:.8}]}>{busy?<ActivityIndicator color={secondary?colors.teal:'#fff'}/>:<Text style={[s.buttonText,secondary&&{color:colors.ink}]}>{label}</Text>}</Pressable>;}
export function Field({label,value,onChangeText,secret=false,multiline=false,keyboardType='default',placeholder}:{label:string;value:string;onChangeText:(text:string)=>void;secret?:boolean;multiline?:boolean;keyboardType?:'default'|'numeric'|'email-address'|'phone-pad';placeholder?:string}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} secureTextEntry={secret} autoCapitalize="none" autoCorrect={false} multiline={multiline} keyboardType={keyboardType} placeholder={placeholder} placeholderTextColor={colors.muted} style={[s.input,multiline&&{minHeight:95,textAlignVertical:'top'}]} textContentType={secret?'password':undefined}/></View>;}
export function ErrorText({message}:{message:string}){return message?<Text accessibilityRole="alert" style={s.error}>{message}</Text>:null;}
export const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.bg},page:{padding:22,paddingBottom:45},brand:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:28},brandText:{fontSize:27,fontWeight:'800',color:colors.ink},caption:{fontSize:8,letterSpacing:1.3,color:colors.muted},title:{fontSize:28,fontWeight:'700',color:colors.ink,marginBottom:9},muted:{color:colors.muted,fontSize:14,lineHeight:22,marginBottom:16},card:{backgroundColor:'#fff',padding:20,borderRadius:15,borderWidth:1,borderColor:colors.line,marginTop:16},heading:{fontSize:19,fontWeight:'700',color:colors.ink,marginBottom:9},text:{fontSize:14,lineHeight:23,color:colors.ink},badge:{color:colors.teal,backgroundColor:'#e5f4f2',paddingHorizontal:10,paddingVertical:6,borderRadius:7,fontSize:12,alignSelf:'flex-start',marginVertical:9},button:{backgroundColor:colors.teal,minHeight:48,borderRadius:9,alignItems:'center',justifyContent:'center',padding:13,marginTop:12},buttonText:{color:'#fff',fontWeight:'600',fontSize:14},secondary:{backgroundColor:'#fff',borderWidth:1,borderColor:colors.line},field:{marginTop:15},label:{fontSize:13,fontWeight:'600',color:colors.ink,marginBottom:7},input:{backgroundColor:'#fff',padding:13,borderRadius:9,borderWidth:1,borderColor:colors.line,fontSize:16,color:colors.ink,minHeight:48},error:{backgroundColor:'#ffebe9',color:'#913d36',padding:14,borderRadius:8,marginTop:14,lineHeight:22},row:{flexDirection:'row',gap:10,alignItems:'center'},stat:{flex:1,padding:17,backgroundColor:'#fff',borderWidth:1,borderColor:colors.line,borderRadius:12},number:{fontSize:30,fontWeight:'700',color:colors.teal},tabs:{flexDirection:'row',gap:8,marginVertical:14},tab:{flex:1,padding:12,borderRadius:9,backgroundColor:'#fff',alignItems:'center'},tabActive:{backgroundColor:'#dff2f0'},small:{color:colors.muted,fontSize:12,lineHeight:20,marginTop:7}});
