# Generated by Django 5.2.17 on 2026-10-06 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0001_initial'),
        ('otp_totp', '0003_add_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilesession',
            name='mfa_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otp_totp.totpdevice'),
        ),
        migrations.AddField(
            model_name='mobilesession',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
