# Generated by Django 5.2.17 on 2026-10-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("held", "Held"),
                    ("confirmed", "Confirmed"),
                    ("arrived", "Arrived"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No-show"),
                ],
                default="requested",
                max_length=16,
            ),
        ),
    ]
