# Generated by Django 5.2.17 on 2026-10-02 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scheduling", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=40)),
                ("event_id", models.CharField(max_length=200)),
                ("event_type", models.CharField(max_length=100)),
                ("signature_verified", models.BooleanField(default=False)),
                ("processed", models.BooleanField(default=False)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "event_id"), name="uq_payment_webhook_event"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DepositPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(max_length=40)),
                ("provider_reference", models.CharField(blank=True, max_length=160)),
                (
                    "idempotency_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("amount_cents", models.PositiveIntegerField()),
                ("currency", models.CharField(default="ZAR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="created",
                        max_length=16,
                    ),
                ),
                ("checkout_url", models.URLField(blank=True, max_length=500)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposit_payments",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.practice",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["practice", "status", "created_at"],
                        name="payments_de_practic_d5cdd6_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount_cents__gt", 0)),
                        name="deposit_amount_greater_than_zero",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("provider_reference", ""), _negated=True),
                        fields=("provider", "provider_reference"),
                        name="uq_payment_provider_reference",
                    ),
                ],
            },
        ),
    ]
