# Generated by Django 5.2.17 on 2026-10-07 13:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('patients', '0002_patient_address'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocumentScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Scanned document', max_length=160)),
                ('original_key', models.CharField(max_length=500, unique=True)),
                ('pdf_key', models.CharField(max_length=500, unique=True)),
                ('original_content_type', models.CharField(max_length=100)),
                ('original_sha256', models.CharField(max_length=64)),
                ('extracted_text', models.TextField(blank=True)),
                ('reviewed_text', models.TextField(blank=True)),
                ('suggestions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scanned_documents', to='patients.patient')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.practice')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
