# Generated by Django 5.2.17 on 2026-10-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_patientdocumentscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocumentscan',
            name='document_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
